// <auto-generated />
using System;
using ComplianceService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplianceService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compliance")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplianceService.Domain.ApplicationProfile.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Owner");

                    b.ToTable("Applications", "compliance");
                });

            modelBuilder.Entity("ComplianceService.Domain.ApplicationProfile.Entities.EnvironmentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId1")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("RiskTier");

                    b.Property<string>("_policiesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Policies");

                    b.Property<string>("_securityToolsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SecurityTools");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId1");

                    b.HasIndex("ApplicationId", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("EnvironmentConfigs", "compliance");
                });

            modelBuilder.Entity("ComplianceService.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluationDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("EvaluationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HighCount")
                        .HasColumnType("integer");

                    b.Property<int>("LowCount")
                        .HasColumnType("integer");

                    b.Property<int>("MediumCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalVulnerabilityCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_violationsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Violations");

                    b.HasKey("Id");

                    b.HasIndex("Allowed");

                    b.HasIndex("ApplicationName");

                    b.HasIndex("Environment");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ApplicationName", "Environment", "EvaluatedAt");

                    b.ToTable("AuditLogs", "compliance", t =>
                        {
                            t.HasComment("Partitioned by EvaluatedAt (monthly) for scalability");
                        });
                });

            modelBuilder.Entity("ComplianceService.Domain.Evaluation.ComplianceEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_decisionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Decision");

                    b.Property<string>("_scanResultsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ScanResults");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Environment");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("ApplicationId", "Environment", "EvaluatedAt");

                    b.ToTable("ComplianceEvaluations", "compliance");
                });

            modelBuilder.Entity("ComplianceService.Domain.ApplicationProfile.Entities.EnvironmentConfig", b =>
                {
                    b.HasOne("ComplianceService.Domain.ApplicationProfile.Application", null)
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplianceService.Domain.ApplicationProfile.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId1");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ComplianceService.Domain.Audit.AuditLog", b =>
                {
                    b.OwnsOne("ComplianceService.Domain.Audit.ValueObjects.DecisionEvidence", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("AuditLogId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EvidenceCapturedAt");

                            b1.Property<string>("PolicyInputJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("EvidencePolicyInput");

                            b1.Property<string>("PolicyOutputJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("EvidencePolicyOutput");

                            b1.Property<string>("ScanResultsJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("EvidenceScanResults");

                            b1.HasKey("AuditLogId");

                            b1.ToTable("AuditLogs", "compliance");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogId");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();
                });

            modelBuilder.Entity("ComplianceService.Domain.ApplicationProfile.Application", b =>
                {
                    b.Navigation("Environments");
                });
#pragma warning restore 612, 618
        }
    }
}
